### ISSUE TITLE
Does not seem to work anymore

### ISSUE THREAD

**Issue by vmpg** [plod/stravaKudos#17]
Since a few days it doesn't work anymore.Seems like Strava changed something on their site.

**Comment by prbreezy** [comment]
I'm also intersted into it, any information on how this should be set up would be use ful.

I configure it on docker on my nas synology but keep telling me this ; 
<div class="x-grid3-row x-grid3-row-over x-grid3-row-selected" id="ext-gen9613" style="margin: 0px; padding: 0px; touch-action: none; border-width: 0px 0px 1px; border-style: dotted dotted solid; border-color: rgb(220, 230, 240) rgb(220, 230, 240) rgb(235, 240, 245); border-image: initial; cursor: default; width: 1196px; background-image: none; background-position: left top; background-size: initial; background-repeat: repeat-x; background-attachment: initial; background-origin: initial; background-clip: initial; background-color: rgb(222, 236, 252) !important; color: rgb(80, 90, 100); font-size: 12px; height: 24px;">

/run.sh: 27: /run.sh: RUN: not found | stdout
-- | --


</div><div class="x-grid3-row x-grid3-row-last" id="ext-gen9611" style="margin: 0px; padding: 0px; touch-action: none; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 1196px; background-color: transparent; color: rgb(80, 90, 100); font-size: 12px; height: 24px;"><table class="x-grid3-row-table" border="0" cellspacing="0" cellpadding="0" style="table-layout: fixed; width: 1196px; height: 24px;"><tbody><tr role="row" id="ext-gen9609" aria-haspopup="true" aria-selected="false"><td class="x-grid3-col x-grid3-cell x-grid3-td-time x-grid3-cell-first " role="gridcell" tabindex="-1" id="ext-gen9606" aria-readonly="true" style="margin: 0px; padding: 0px 1px; outline: 0px; line-height: 13px; vertical-align: top; font-weight: 400; font-size: 11px; height: 24px; color: rgb(80, 90, 100); font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: 147px;"><div class="x-grid3-cell-inner x-grid3-col-time x-unselectable" unselectable="on" style="margin: 0px; padding: 0px 8px; touch-action: none; user-select: none; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: rgb(80, 90, 100); font-size: 12px; width: auto; line-height: 24px;">06:23:07</div></td><td class="x-grid3-col x-grid3-cell x-grid3-td-1 " role="gridcell" tabindex="-1" id="ext-gen9607" aria-readonly="true" style="margin: 0px; padding: 0px 1px; outline: 0px; line-height: 13px; vertical-align: top; font-weight: 400; font-size: 11px; height: 24px; color: rgb(80, 90, 100); font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; width: 895px;"><div class="x-grid3-cell-inner x-grid3-col-1 x-unselectable" unselectable="on" style="margin: 0px; padding: 0px 8px; touch-action: none; user-select: none; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: rgb(80, 90, 100); font-size: 12px; width: auto; line-height: 24px;"><br class="Apple-interchange-newline">

**Comment by vmpg** [comment]
> I'm also intersted into it, any information on how this should be set up would be use ful.
> 
> I configure it on docker on my nas synology but keep telling me this ;
> 
> /run.sh: 27: /run.sh: RUN: not found	stdout
> 06:23:07

I now have a working version again.
Best you take the version of tonymet that is much better.

https://github.com/tonymet/stravaKudos
